/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "RpcService_constants.h"

namespace jsbn { namespace rpc { namespace bc {

const RpcServiceConstants g_RpcService_constants;

RpcServiceConstants::RpcServiceConstants() {
}

}}} // namespace

