/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RpcService_CONSTANTS_H
#define RpcService_CONSTANTS_H

#include "RpcService_types.h"

namespace jsbn { namespace rpc { namespace bc {

class RpcServiceConstants {
 public:
  RpcServiceConstants();

};

extern const RpcServiceConstants g_RpcService_constants;

}}} // namespace

#endif
