// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#ifndef __RPC_SERVICE_HANDLER_H_
#define __RPC_SERVICE_HANDLER_H_
#include "RpcService.h"

using namespace  ::jsbn::rpc::bc;

class RpcServiceHandler : virtual public RpcServiceIf
{
 public:
  RpcServiceHandler();

  bool postUserInfo(const UserInfo& userInfo);

  void searchUserInfos(UserInfoSearchResult& _return, const std::string& query);

  void hello();

};

#endif
