/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RpcService_H
#define RpcService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "RpcService_types.h"

namespace jsbn { namespace rpc { namespace bc {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class RpcServiceIf {
 public:
  virtual ~RpcServiceIf() {}
  virtual bool postUserInfo(const UserInfo& userInfo) = 0;
  virtual void searchUserInfos(UserInfoSearchResult& _return, const std::string& query) = 0;
  virtual void hello() = 0;
};

class RpcServiceIfFactory {
 public:
  typedef RpcServiceIf Handler;

  virtual ~RpcServiceIfFactory() {}

  virtual RpcServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RpcServiceIf* /* handler */) = 0;
};

class RpcServiceIfSingletonFactory : virtual public RpcServiceIfFactory {
 public:
  RpcServiceIfSingletonFactory(const boost::shared_ptr<RpcServiceIf>& iface) : iface_(iface) {}
  virtual ~RpcServiceIfSingletonFactory() {}

  virtual RpcServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(RpcServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<RpcServiceIf> iface_;
};

class RpcServiceNull : virtual public RpcServiceIf {
 public:
  virtual ~RpcServiceNull() {}
  bool postUserInfo(const UserInfo& /* userInfo */) {
    bool _return = false;
    return _return;
  }
  void searchUserInfos(UserInfoSearchResult& /* _return */, const std::string& /* query */) {
    return;
  }
  void hello() {
    return;
  }
};

typedef struct _RpcService_postUserInfo_args__isset {
  _RpcService_postUserInfo_args__isset() : userInfo(false) {}
  bool userInfo :1;
} _RpcService_postUserInfo_args__isset;

class RpcService_postUserInfo_args {
 public:

  RpcService_postUserInfo_args(const RpcService_postUserInfo_args&);
  RpcService_postUserInfo_args& operator=(const RpcService_postUserInfo_args&);
  RpcService_postUserInfo_args() {
  }

  virtual ~RpcService_postUserInfo_args() throw();
  UserInfo userInfo;

  _RpcService_postUserInfo_args__isset __isset;

  void __set_userInfo(const UserInfo& val);

  bool operator == (const RpcService_postUserInfo_args & rhs) const
  {
    if (!(userInfo == rhs.userInfo))
      return false;
    return true;
  }
  bool operator != (const RpcService_postUserInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RpcService_postUserInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RpcService_postUserInfo_pargs {
 public:


  virtual ~RpcService_postUserInfo_pargs() throw();
  const UserInfo* userInfo;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RpcService_postUserInfo_result__isset {
  _RpcService_postUserInfo_result__isset() : success(false), unavailable(false) {}
  bool success :1;
  bool unavailable :1;
} _RpcService_postUserInfo_result__isset;

class RpcService_postUserInfo_result {
 public:

  RpcService_postUserInfo_result(const RpcService_postUserInfo_result&);
  RpcService_postUserInfo_result& operator=(const RpcService_postUserInfo_result&);
  RpcService_postUserInfo_result() : success(0) {
  }

  virtual ~RpcService_postUserInfo_result() throw();
  bool success;
  Unavailable unavailable;

  _RpcService_postUserInfo_result__isset __isset;

  void __set_success(const bool val);

  void __set_unavailable(const Unavailable& val);

  bool operator == (const RpcService_postUserInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(unavailable == rhs.unavailable))
      return false;
    return true;
  }
  bool operator != (const RpcService_postUserInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RpcService_postUserInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RpcService_postUserInfo_presult__isset {
  _RpcService_postUserInfo_presult__isset() : success(false), unavailable(false) {}
  bool success :1;
  bool unavailable :1;
} _RpcService_postUserInfo_presult__isset;

class RpcService_postUserInfo_presult {
 public:


  virtual ~RpcService_postUserInfo_presult() throw();
  bool* success;
  Unavailable unavailable;

  _RpcService_postUserInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _RpcService_searchUserInfos_args__isset {
  _RpcService_searchUserInfos_args__isset() : query(false) {}
  bool query :1;
} _RpcService_searchUserInfos_args__isset;

class RpcService_searchUserInfos_args {
 public:

  RpcService_searchUserInfos_args(const RpcService_searchUserInfos_args&);
  RpcService_searchUserInfos_args& operator=(const RpcService_searchUserInfos_args&);
  RpcService_searchUserInfos_args() : query() {
  }

  virtual ~RpcService_searchUserInfos_args() throw();
  std::string query;

  _RpcService_searchUserInfos_args__isset __isset;

  void __set_query(const std::string& val);

  bool operator == (const RpcService_searchUserInfos_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const RpcService_searchUserInfos_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RpcService_searchUserInfos_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RpcService_searchUserInfos_pargs {
 public:


  virtual ~RpcService_searchUserInfos_pargs() throw();
  const std::string* query;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RpcService_searchUserInfos_result__isset {
  _RpcService_searchUserInfos_result__isset() : success(false) {}
  bool success :1;
} _RpcService_searchUserInfos_result__isset;

class RpcService_searchUserInfos_result {
 public:

  RpcService_searchUserInfos_result(const RpcService_searchUserInfos_result&);
  RpcService_searchUserInfos_result& operator=(const RpcService_searchUserInfos_result&);
  RpcService_searchUserInfos_result() {
  }

  virtual ~RpcService_searchUserInfos_result() throw();
  UserInfoSearchResult success;

  _RpcService_searchUserInfos_result__isset __isset;

  void __set_success(const UserInfoSearchResult& val);

  bool operator == (const RpcService_searchUserInfos_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RpcService_searchUserInfos_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RpcService_searchUserInfos_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RpcService_searchUserInfos_presult__isset {
  _RpcService_searchUserInfos_presult__isset() : success(false) {}
  bool success :1;
} _RpcService_searchUserInfos_presult__isset;

class RpcService_searchUserInfos_presult {
 public:


  virtual ~RpcService_searchUserInfos_presult() throw();
  UserInfoSearchResult* success;

  _RpcService_searchUserInfos_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class RpcService_hello_args {
 public:

  RpcService_hello_args(const RpcService_hello_args&);
  RpcService_hello_args& operator=(const RpcService_hello_args&);
  RpcService_hello_args() {
  }

  virtual ~RpcService_hello_args() throw();

  bool operator == (const RpcService_hello_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const RpcService_hello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RpcService_hello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RpcService_hello_pargs {
 public:


  virtual ~RpcService_hello_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class RpcServiceClient : virtual public RpcServiceIf {
 public:
  RpcServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RpcServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool postUserInfo(const UserInfo& userInfo);
  void send_postUserInfo(const UserInfo& userInfo);
  bool recv_postUserInfo();
  void searchUserInfos(UserInfoSearchResult& _return, const std::string& query);
  void send_searchUserInfos(const std::string& query);
  void recv_searchUserInfos(UserInfoSearchResult& _return);
  void hello();
  void send_hello();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RpcServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<RpcServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (RpcServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_postUserInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_searchUserInfos(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_hello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RpcServiceProcessor(boost::shared_ptr<RpcServiceIf> iface) :
    iface_(iface) {
    processMap_["postUserInfo"] = &RpcServiceProcessor::process_postUserInfo;
    processMap_["searchUserInfos"] = &RpcServiceProcessor::process_searchUserInfos;
    processMap_["hello"] = &RpcServiceProcessor::process_hello;
  }

  virtual ~RpcServiceProcessor() {}
};

class RpcServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RpcServiceProcessorFactory(const ::boost::shared_ptr< RpcServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< RpcServiceIfFactory > handlerFactory_;
};

class RpcServiceMultiface : virtual public RpcServiceIf {
 public:
  RpcServiceMultiface(std::vector<boost::shared_ptr<RpcServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RpcServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<RpcServiceIf> > ifaces_;
  RpcServiceMultiface() {}
  void add(boost::shared_ptr<RpcServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool postUserInfo(const UserInfo& userInfo) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->postUserInfo(userInfo);
    }
    return ifaces_[i]->postUserInfo(userInfo);
  }

  void searchUserInfos(UserInfoSearchResult& _return, const std::string& query) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->searchUserInfos(_return, query);
    }
    ifaces_[i]->searchUserInfos(_return, query);
    return;
  }

  void hello() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->hello();
    }
    ifaces_[i]->hello();
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class RpcServiceConcurrentClient : virtual public RpcServiceIf {
 public:
  RpcServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  RpcServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool postUserInfo(const UserInfo& userInfo);
  int32_t send_postUserInfo(const UserInfo& userInfo);
  bool recv_postUserInfo(const int32_t seqid);
  void searchUserInfos(UserInfoSearchResult& _return, const std::string& query);
  int32_t send_searchUserInfos(const std::string& query);
  void recv_searchUserInfos(UserInfoSearchResult& _return, const int32_t seqid);
  void hello();
  void send_hello();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

}}} // namespace

#endif
