// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsbn_css.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "jsbn_css.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

namespace jsbn {
namespace protoc {

void protobuf_ShutdownFile_jsbn_5fcss_2eproto() {
  delete CSSNetProtocol::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_jsbn_5fcss_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_jsbn_5fcss_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  CSSNetProtocol::default_instance_ = new CSSNetProtocol();
  CSSNetProtocol::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_jsbn_5fcss_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_jsbn_5fcss_2eproto_once_);
void protobuf_AddDesc_jsbn_5fcss_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_jsbn_5fcss_2eproto_once_,
                 &protobuf_AddDesc_jsbn_5fcss_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_jsbn_5fcss_2eproto {
  StaticDescriptorInitializer_jsbn_5fcss_2eproto() {
    protobuf_AddDesc_jsbn_5fcss_2eproto();
  }
} static_descriptor_initializer_jsbn_5fcss_2eproto_;
#endif
bool MSG_IsValid(int value) {
  switch(value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#ifndef _MSC_VER
const int CSSNetProtocol::kTypeFieldNumber;
#endif  // !_MSC_VER

CSSNetProtocol::CSSNetProtocol()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:jsbn.protoc.CSSNetProtocol)
}

void CSSNetProtocol::InitAsDefaultInstance() {
}

CSSNetProtocol::CSSNetProtocol(const CSSNetProtocol& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:jsbn.protoc.CSSNetProtocol)
}

void CSSNetProtocol::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CSSNetProtocol::~CSSNetProtocol() {
  // @@protoc_insertion_point(destructor:jsbn.protoc.CSSNetProtocol)
  SharedDtor();
}

void CSSNetProtocol::SharedDtor() {
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void CSSNetProtocol::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const CSSNetProtocol& CSSNetProtocol::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_jsbn_5fcss_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_jsbn_5fcss_2eproto();
#endif
  return *default_instance_;
}

CSSNetProtocol* CSSNetProtocol::default_instance_ = NULL;

CSSNetProtocol* CSSNetProtocol::New() const {
  return new CSSNetProtocol;
}

void CSSNetProtocol::Clear() {
  type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->clear();
}

bool CSSNetProtocol::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::StringOutputStream unknown_fields_string(
      mutable_unknown_fields());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string);
  // @@protoc_insertion_point(parse_start:jsbn.protoc.CSSNetProtocol)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .jsbn.protoc.MSG type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::jsbn::protoc::MSG_IsValid(value)) {
            set_type(static_cast< ::jsbn::protoc::MSG >(value));
          } else {
            unknown_fields_stream.WriteVarint32(tag);
            unknown_fields_stream.WriteVarint32(value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:jsbn.protoc.CSSNetProtocol)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:jsbn.protoc.CSSNetProtocol)
  return false;
#undef DO_
}

void CSSNetProtocol::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:jsbn.protoc.CSSNetProtocol)
  // required .jsbn.protoc.MSG type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   unknown_fields().size());
  // @@protoc_insertion_point(serialize_end:jsbn.protoc.CSSNetProtocol)
}

int CSSNetProtocol::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .jsbn.protoc.MSG type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CSSNetProtocol::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const CSSNetProtocol*>(&from));
}

void CSSNetProtocol::MergeFrom(const CSSNetProtocol& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->append(from.unknown_fields());
}

void CSSNetProtocol::CopyFrom(const CSSNetProtocol& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSSNetProtocol::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CSSNetProtocol::Swap(CSSNetProtocol* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.swap(other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string CSSNetProtocol::GetTypeName() const {
  return "jsbn.protoc.CSSNetProtocol";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protoc
}  // namespace jsbn

// @@protoc_insertion_point(global_scope)
