// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jsbn_css.proto

#ifndef PROTOBUF_jsbn_5fcss_2eproto__INCLUDED
#define PROTOBUF_jsbn_5fcss_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace jsbn {
namespace protoc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_jsbn_5fcss_2eproto();
void protobuf_AssignDesc_jsbn_5fcss_2eproto();
void protobuf_ShutdownFile_jsbn_5fcss_2eproto();

class CSSNetProtocol;

enum MSG {
  Heart_Beat = 0
};
bool MSG_IsValid(int value);
const MSG MSG_MIN = Heart_Beat;
const MSG MSG_MAX = Heart_Beat;
const int MSG_ARRAYSIZE = MSG_MAX + 1;

// ===================================================================

class CSSNetProtocol : public ::google::protobuf::MessageLite {
 public:
  CSSNetProtocol();
  virtual ~CSSNetProtocol();

  CSSNetProtocol(const CSSNetProtocol& from);

  inline CSSNetProtocol& operator=(const CSSNetProtocol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const CSSNetProtocol& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const CSSNetProtocol* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(CSSNetProtocol* other);

  // implements Message ----------------------------------------------

  CSSNetProtocol* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const CSSNetProtocol& from);
  void MergeFrom(const CSSNetProtocol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .jsbn.protoc.MSG type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::jsbn::protoc::MSG type() const;
  inline void set_type(::jsbn::protoc::MSG value);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.CSSNetProtocol)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_jsbn_5fcss_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_jsbn_5fcss_2eproto();
  #endif
  friend void protobuf_AssignDesc_jsbn_5fcss_2eproto();
  friend void protobuf_ShutdownFile_jsbn_5fcss_2eproto();

  void InitAsDefaultInstance();
  static CSSNetProtocol* default_instance_;
};
// ===================================================================


// ===================================================================

// CSSNetProtocol

// required .jsbn.protoc.MSG type = 1;
inline bool CSSNetProtocol::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CSSNetProtocol::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CSSNetProtocol::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CSSNetProtocol::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::jsbn::protoc::MSG CSSNetProtocol::type() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.CSSNetProtocol.type)
  return static_cast< ::jsbn::protoc::MSG >(type_);
}
inline void CSSNetProtocol::set_type(::jsbn::protoc::MSG value) {
  assert(::jsbn::protoc::MSG_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.CSSNetProtocol.type)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protoc
}  // namespace jsbn

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_jsbn_5fcss_2eproto__INCLUDED
