// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc.proto

#ifndef PROTOBUF_protoc_2eproto__INCLUDED
#define PROTOBUF_protoc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace jsbn {
namespace protoc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protoc_2eproto();
void protobuf_AssignDesc_protoc_2eproto();
void protobuf_ShutdownFile_protoc_2eproto();

class RegisterReq;
class RegisterRsp;
class DataRelayReq;
class DataRelayRsp;
class NetProtocol;

enum CityID {
  CID_INIT = -1,
  CID_CQ = 0,
  CID_CD = 1,
  CID_HZ = 2
};
bool CityID_IsValid(int value);
const CityID CityID_MIN = CID_INIT;
const CityID CityID_MAX = CID_HZ;
const int CityID_ARRAYSIZE = CityID_MAX + 1;

enum ServiceTpye {
  ST_INIT = -1,
  ST_CSS = 0,
  ST_BSS = 1,
  ST_SMS = 2,
  ST_CMS = 3
};
bool ServiceTpye_IsValid(int value);
const ServiceTpye ServiceTpye_MIN = ST_INIT;
const ServiceTpye ServiceTpye_MAX = ST_CMS;
const int ServiceTpye_ARRAYSIZE = ServiceTpye_MAX + 1;

enum CommandID {
  Heart_Beat = 0,
  Register_Req = 1,
  Register_Rsp = 65537,
  Data_Relay_Req = 2,
  Data_Relay_Rsp = 65538
};
bool CommandID_IsValid(int value);
const CommandID CommandID_MIN = Heart_Beat;
const CommandID CommandID_MAX = Data_Relay_Rsp;
const int CommandID_ARRAYSIZE = CommandID_MAX + 1;

// ===================================================================

class RegisterReq : public ::google::protobuf::MessageLite {
 public:
  RegisterReq();
  virtual ~RegisterReq();

  RegisterReq(const RegisterReq& from);

  inline RegisterReq& operator=(const RegisterReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const RegisterReq& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RegisterReq* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RegisterReq* other);

  // implements Message ----------------------------------------------

  RegisterReq* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RegisterReq& from);
  void MergeFrom(const RegisterReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .jsbn.protoc.CityID cityID = 1;
  inline bool has_cityid() const;
  inline void clear_cityid();
  static const int kCityIDFieldNumber = 1;
  inline ::jsbn::protoc::CityID cityid() const;
  inline void set_cityid(::jsbn::protoc::CityID value);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.RegisterReq)
 private:
  inline void set_has_cityid();
  inline void clear_has_cityid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int cityid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static RegisterReq* default_instance_;
};
// -------------------------------------------------------------------

class RegisterRsp : public ::google::protobuf::MessageLite {
 public:
  RegisterRsp();
  virtual ~RegisterRsp();

  RegisterRsp(const RegisterRsp& from);

  inline RegisterRsp& operator=(const RegisterRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const RegisterRsp& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RegisterRsp* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RegisterRsp* other);

  // implements Message ----------------------------------------------

  RegisterRsp* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RegisterRsp& from);
  void MergeFrom(const RegisterRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::uint32 result() const;
  inline void set_result(::google::protobuf::uint32 value);

  // optional string error_description = 2;
  inline bool has_error_description() const;
  inline void clear_error_description();
  static const int kErrorDescriptionFieldNumber = 2;
  inline const ::std::string& error_description() const;
  inline void set_error_description(const ::std::string& value);
  inline void set_error_description(const char* value);
  inline void set_error_description(const char* value, size_t size);
  inline ::std::string* mutable_error_description();
  inline ::std::string* release_error_description();
  inline void set_allocated_error_description(::std::string* error_description);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.RegisterRsp)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_error_description();
  inline void clear_has_error_description();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* error_description_;
  ::google::protobuf::uint32 result_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static RegisterRsp* default_instance_;
};
// -------------------------------------------------------------------

class DataRelayReq : public ::google::protobuf::MessageLite {
 public:
  DataRelayReq();
  virtual ~DataRelayReq();

  DataRelayReq(const DataRelayReq& from);

  inline DataRelayReq& operator=(const DataRelayReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DataRelayReq& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DataRelayReq* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DataRelayReq* other);

  // implements Message ----------------------------------------------

  DataRelayReq* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DataRelayReq& from);
  void MergeFrom(const DataRelayReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .jsbn.protoc.ServiceTpye srcSrvType = 1;
  inline bool has_srcsrvtype() const;
  inline void clear_srcsrvtype();
  static const int kSrcSrvTypeFieldNumber = 1;
  inline ::jsbn::protoc::ServiceTpye srcsrvtype() const;
  inline void set_srcsrvtype(::jsbn::protoc::ServiceTpye value);

  // required .jsbn.protoc.ServiceTpye dstSrvType = 2;
  inline bool has_dstsrvtype() const;
  inline void clear_dstsrvtype();
  static const int kDstSrvTypeFieldNumber = 2;
  inline ::jsbn::protoc::ServiceTpye dstsrvtype() const;
  inline void set_dstsrvtype(::jsbn::protoc::ServiceTpye value);

  // optional .jsbn.protoc.CityID dstCityID = 3;
  inline bool has_dstcityid() const;
  inline void clear_dstcityid();
  static const int kDstCityIDFieldNumber = 3;
  inline ::jsbn::protoc::CityID dstcityid() const;
  inline void set_dstcityid(::jsbn::protoc::CityID value);

  // optional string relayMsgStr = 4;
  inline bool has_relaymsgstr() const;
  inline void clear_relaymsgstr();
  static const int kRelayMsgStrFieldNumber = 4;
  inline const ::std::string& relaymsgstr() const;
  inline void set_relaymsgstr(const ::std::string& value);
  inline void set_relaymsgstr(const char* value);
  inline void set_relaymsgstr(const char* value, size_t size);
  inline ::std::string* mutable_relaymsgstr();
  inline ::std::string* release_relaymsgstr();
  inline void set_allocated_relaymsgstr(::std::string* relaymsgstr);

  // optional bytes relayMsgBytes = 5;
  inline bool has_relaymsgbytes() const;
  inline void clear_relaymsgbytes();
  static const int kRelayMsgBytesFieldNumber = 5;
  inline const ::std::string& relaymsgbytes() const;
  inline void set_relaymsgbytes(const ::std::string& value);
  inline void set_relaymsgbytes(const char* value);
  inline void set_relaymsgbytes(const void* value, size_t size);
  inline ::std::string* mutable_relaymsgbytes();
  inline ::std::string* release_relaymsgbytes();
  inline void set_allocated_relaymsgbytes(::std::string* relaymsgbytes);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.DataRelayReq)
 private:
  inline void set_has_srcsrvtype();
  inline void clear_has_srcsrvtype();
  inline void set_has_dstsrvtype();
  inline void clear_has_dstsrvtype();
  inline void set_has_dstcityid();
  inline void clear_has_dstcityid();
  inline void set_has_relaymsgstr();
  inline void clear_has_relaymsgstr();
  inline void set_has_relaymsgbytes();
  inline void clear_has_relaymsgbytes();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int srcsrvtype_;
  int dstsrvtype_;
  ::std::string* relaymsgstr_;
  ::std::string* relaymsgbytes_;
  int dstcityid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static DataRelayReq* default_instance_;
};
// -------------------------------------------------------------------

class DataRelayRsp : public ::google::protobuf::MessageLite {
 public:
  DataRelayRsp();
  virtual ~DataRelayRsp();

  DataRelayRsp(const DataRelayRsp& from);

  inline DataRelayRsp& operator=(const DataRelayRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const DataRelayRsp& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const DataRelayRsp* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(DataRelayRsp* other);

  // implements Message ----------------------------------------------

  DataRelayRsp* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const DataRelayRsp& from);
  void MergeFrom(const DataRelayRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .jsbn.protoc.ServiceTpye srcSrvType = 1;
  inline bool has_srcsrvtype() const;
  inline void clear_srcsrvtype();
  static const int kSrcSrvTypeFieldNumber = 1;
  inline ::jsbn::protoc::ServiceTpye srcsrvtype() const;
  inline void set_srcsrvtype(::jsbn::protoc::ServiceTpye value);

  // required .jsbn.protoc.ServiceTpye dstSrvType = 2;
  inline bool has_dstsrvtype() const;
  inline void clear_dstsrvtype();
  static const int kDstSrvTypeFieldNumber = 2;
  inline ::jsbn::protoc::ServiceTpye dstsrvtype() const;
  inline void set_dstsrvtype(::jsbn::protoc::ServiceTpye value);

  // optional .jsbn.protoc.CityID dstCityID = 3;
  inline bool has_dstcityid() const;
  inline void clear_dstcityid();
  static const int kDstCityIDFieldNumber = 3;
  inline ::jsbn::protoc::CityID dstcityid() const;
  inline void set_dstcityid(::jsbn::protoc::CityID value);

  // required fixed32 result = 4;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 4;
  inline ::google::protobuf::uint32 result() const;
  inline void set_result(::google::protobuf::uint32 value);

  // optional string error_description = 5;
  inline bool has_error_description() const;
  inline void clear_error_description();
  static const int kErrorDescriptionFieldNumber = 5;
  inline const ::std::string& error_description() const;
  inline void set_error_description(const ::std::string& value);
  inline void set_error_description(const char* value);
  inline void set_error_description(const char* value, size_t size);
  inline ::std::string* mutable_error_description();
  inline ::std::string* release_error_description();
  inline void set_allocated_error_description(::std::string* error_description);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.DataRelayRsp)
 private:
  inline void set_has_srcsrvtype();
  inline void clear_has_srcsrvtype();
  inline void set_has_dstsrvtype();
  inline void clear_has_dstsrvtype();
  inline void set_has_dstcityid();
  inline void clear_has_dstcityid();
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_error_description();
  inline void clear_has_error_description();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int srcsrvtype_;
  int dstsrvtype_;
  int dstcityid_;
  ::google::protobuf::uint32 result_;
  ::std::string* error_description_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static DataRelayRsp* default_instance_;
};
// -------------------------------------------------------------------

class NetProtocol : public ::google::protobuf::MessageLite {
 public:
  NetProtocol();
  virtual ~NetProtocol();

  NetProtocol(const NetProtocol& from);

  inline NetProtocol& operator=(const NetProtocol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const NetProtocol& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const NetProtocol* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(NetProtocol* other);

  // implements Message ----------------------------------------------

  NetProtocol* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const NetProtocol& from);
  void MergeFrom(const NetProtocol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional fixed32 seq = 1;
  inline bool has_seq() const;
  inline void clear_seq();
  static const int kSeqFieldNumber = 1;
  inline ::google::protobuf::uint32 seq() const;
  inline void set_seq(::google::protobuf::uint32 value);

  // required .jsbn.protoc.CommandID commandID = 2;
  inline bool has_commandid() const;
  inline void clear_commandid();
  static const int kCommandIDFieldNumber = 2;
  inline ::jsbn::protoc::CommandID commandid() const;
  inline void set_commandid(::jsbn::protoc::CommandID value);

  // optional .jsbn.protoc.RegisterReq registerReq = 3;
  inline bool has_registerreq() const;
  inline void clear_registerreq();
  static const int kRegisterReqFieldNumber = 3;
  inline const ::jsbn::protoc::RegisterReq& registerreq() const;
  inline ::jsbn::protoc::RegisterReq* mutable_registerreq();
  inline ::jsbn::protoc::RegisterReq* release_registerreq();
  inline void set_allocated_registerreq(::jsbn::protoc::RegisterReq* registerreq);

  // optional .jsbn.protoc.RegisterRsp registerRsp = 4;
  inline bool has_registerrsp() const;
  inline void clear_registerrsp();
  static const int kRegisterRspFieldNumber = 4;
  inline const ::jsbn::protoc::RegisterRsp& registerrsp() const;
  inline ::jsbn::protoc::RegisterRsp* mutable_registerrsp();
  inline ::jsbn::protoc::RegisterRsp* release_registerrsp();
  inline void set_allocated_registerrsp(::jsbn::protoc::RegisterRsp* registerrsp);

  // optional .jsbn.protoc.DataRelayReq dataRelayReq = 5;
  inline bool has_datarelayreq() const;
  inline void clear_datarelayreq();
  static const int kDataRelayReqFieldNumber = 5;
  inline const ::jsbn::protoc::DataRelayReq& datarelayreq() const;
  inline ::jsbn::protoc::DataRelayReq* mutable_datarelayreq();
  inline ::jsbn::protoc::DataRelayReq* release_datarelayreq();
  inline void set_allocated_datarelayreq(::jsbn::protoc::DataRelayReq* datarelayreq);

  // optional .jsbn.protoc.DataRelayRsp dataRelayRsp = 6;
  inline bool has_datarelayrsp() const;
  inline void clear_datarelayrsp();
  static const int kDataRelayRspFieldNumber = 6;
  inline const ::jsbn::protoc::DataRelayRsp& datarelayrsp() const;
  inline ::jsbn::protoc::DataRelayRsp* mutable_datarelayrsp();
  inline ::jsbn::protoc::DataRelayRsp* release_datarelayrsp();
  inline void set_allocated_datarelayrsp(::jsbn::protoc::DataRelayRsp* datarelayrsp);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.NetProtocol)
 private:
  inline void set_has_seq();
  inline void clear_has_seq();
  inline void set_has_commandid();
  inline void clear_has_commandid();
  inline void set_has_registerreq();
  inline void clear_has_registerreq();
  inline void set_has_registerrsp();
  inline void clear_has_registerrsp();
  inline void set_has_datarelayreq();
  inline void clear_has_datarelayreq();
  inline void set_has_datarelayrsp();
  inline void clear_has_datarelayrsp();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 seq_;
  int commandid_;
  ::jsbn::protoc::RegisterReq* registerreq_;
  ::jsbn::protoc::RegisterRsp* registerrsp_;
  ::jsbn::protoc::DataRelayReq* datarelayreq_;
  ::jsbn::protoc::DataRelayRsp* datarelayrsp_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static NetProtocol* default_instance_;
};
// ===================================================================


// ===================================================================

// RegisterReq

// required .jsbn.protoc.CityID cityID = 1;
inline bool RegisterReq::has_cityid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterReq::set_has_cityid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterReq::clear_has_cityid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterReq::clear_cityid() {
  cityid_ = -1;
  clear_has_cityid();
}
inline ::jsbn::protoc::CityID RegisterReq::cityid() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.RegisterReq.cityID)
  return static_cast< ::jsbn::protoc::CityID >(cityid_);
}
inline void RegisterReq::set_cityid(::jsbn::protoc::CityID value) {
  assert(::jsbn::protoc::CityID_IsValid(value));
  set_has_cityid();
  cityid_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.RegisterReq.cityID)
}

// -------------------------------------------------------------------

// RegisterRsp

// required fixed32 result = 1;
inline bool RegisterRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterRsp::clear_result() {
  result_ = 0u;
  clear_has_result();
}
inline ::google::protobuf::uint32 RegisterRsp::result() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.RegisterRsp.result)
  return result_;
}
inline void RegisterRsp::set_result(::google::protobuf::uint32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.RegisterRsp.result)
}

// optional string error_description = 2;
inline bool RegisterRsp::has_error_description() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterRsp::set_has_error_description() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegisterRsp::clear_has_error_description() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegisterRsp::clear_error_description() {
  if (error_description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_->clear();
  }
  clear_has_error_description();
}
inline const ::std::string& RegisterRsp::error_description() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.RegisterRsp.error_description)
  return *error_description_;
}
inline void RegisterRsp::set_error_description(const ::std::string& value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
  // @@protoc_insertion_point(field_set:jsbn.protoc.RegisterRsp.error_description)
}
inline void RegisterRsp::set_error_description(const char* value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
  // @@protoc_insertion_point(field_set_char:jsbn.protoc.RegisterRsp.error_description)
}
inline void RegisterRsp::set_error_description(const char* value, size_t size) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:jsbn.protoc.RegisterRsp.error_description)
}
inline ::std::string* RegisterRsp::mutable_error_description() {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.RegisterRsp.error_description)
  return error_description_;
}
inline ::std::string* RegisterRsp::release_error_description() {
  clear_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = error_description_;
    error_description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterRsp::set_allocated_error_description(::std::string* error_description) {
  if (error_description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_description_;
  }
  if (error_description) {
    set_has_error_description();
    error_description_ = error_description;
  } else {
    clear_has_error_description();
    error_description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.RegisterRsp.error_description)
}

// -------------------------------------------------------------------

// DataRelayReq

// required .jsbn.protoc.ServiceTpye srcSrvType = 1;
inline bool DataRelayReq::has_srcsrvtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataRelayReq::set_has_srcsrvtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataRelayReq::clear_has_srcsrvtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataRelayReq::clear_srcsrvtype() {
  srcsrvtype_ = -1;
  clear_has_srcsrvtype();
}
inline ::jsbn::protoc::ServiceTpye DataRelayReq::srcsrvtype() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayReq.srcSrvType)
  return static_cast< ::jsbn::protoc::ServiceTpye >(srcsrvtype_);
}
inline void DataRelayReq::set_srcsrvtype(::jsbn::protoc::ServiceTpye value) {
  assert(::jsbn::protoc::ServiceTpye_IsValid(value));
  set_has_srcsrvtype();
  srcsrvtype_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayReq.srcSrvType)
}

// required .jsbn.protoc.ServiceTpye dstSrvType = 2;
inline bool DataRelayReq::has_dstsrvtype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DataRelayReq::set_has_dstsrvtype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DataRelayReq::clear_has_dstsrvtype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DataRelayReq::clear_dstsrvtype() {
  dstsrvtype_ = -1;
  clear_has_dstsrvtype();
}
inline ::jsbn::protoc::ServiceTpye DataRelayReq::dstsrvtype() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayReq.dstSrvType)
  return static_cast< ::jsbn::protoc::ServiceTpye >(dstsrvtype_);
}
inline void DataRelayReq::set_dstsrvtype(::jsbn::protoc::ServiceTpye value) {
  assert(::jsbn::protoc::ServiceTpye_IsValid(value));
  set_has_dstsrvtype();
  dstsrvtype_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayReq.dstSrvType)
}

// optional .jsbn.protoc.CityID dstCityID = 3;
inline bool DataRelayReq::has_dstcityid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DataRelayReq::set_has_dstcityid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DataRelayReq::clear_has_dstcityid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DataRelayReq::clear_dstcityid() {
  dstcityid_ = -1;
  clear_has_dstcityid();
}
inline ::jsbn::protoc::CityID DataRelayReq::dstcityid() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayReq.dstCityID)
  return static_cast< ::jsbn::protoc::CityID >(dstcityid_);
}
inline void DataRelayReq::set_dstcityid(::jsbn::protoc::CityID value) {
  assert(::jsbn::protoc::CityID_IsValid(value));
  set_has_dstcityid();
  dstcityid_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayReq.dstCityID)
}

// optional string relayMsgStr = 4;
inline bool DataRelayReq::has_relaymsgstr() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DataRelayReq::set_has_relaymsgstr() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DataRelayReq::clear_has_relaymsgstr() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DataRelayReq::clear_relaymsgstr() {
  if (relaymsgstr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgstr_->clear();
  }
  clear_has_relaymsgstr();
}
inline const ::std::string& DataRelayReq::relaymsgstr() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayReq.relayMsgStr)
  return *relaymsgstr_;
}
inline void DataRelayReq::set_relaymsgstr(const ::std::string& value) {
  set_has_relaymsgstr();
  if (relaymsgstr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgstr_ = new ::std::string;
  }
  relaymsgstr_->assign(value);
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayReq.relayMsgStr)
}
inline void DataRelayReq::set_relaymsgstr(const char* value) {
  set_has_relaymsgstr();
  if (relaymsgstr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgstr_ = new ::std::string;
  }
  relaymsgstr_->assign(value);
  // @@protoc_insertion_point(field_set_char:jsbn.protoc.DataRelayReq.relayMsgStr)
}
inline void DataRelayReq::set_relaymsgstr(const char* value, size_t size) {
  set_has_relaymsgstr();
  if (relaymsgstr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgstr_ = new ::std::string;
  }
  relaymsgstr_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:jsbn.protoc.DataRelayReq.relayMsgStr)
}
inline ::std::string* DataRelayReq::mutable_relaymsgstr() {
  set_has_relaymsgstr();
  if (relaymsgstr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgstr_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.DataRelayReq.relayMsgStr)
  return relaymsgstr_;
}
inline ::std::string* DataRelayReq::release_relaymsgstr() {
  clear_has_relaymsgstr();
  if (relaymsgstr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = relaymsgstr_;
    relaymsgstr_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DataRelayReq::set_allocated_relaymsgstr(::std::string* relaymsgstr) {
  if (relaymsgstr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete relaymsgstr_;
  }
  if (relaymsgstr) {
    set_has_relaymsgstr();
    relaymsgstr_ = relaymsgstr;
  } else {
    clear_has_relaymsgstr();
    relaymsgstr_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.DataRelayReq.relayMsgStr)
}

// optional bytes relayMsgBytes = 5;
inline bool DataRelayReq::has_relaymsgbytes() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DataRelayReq::set_has_relaymsgbytes() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DataRelayReq::clear_has_relaymsgbytes() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DataRelayReq::clear_relaymsgbytes() {
  if (relaymsgbytes_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgbytes_->clear();
  }
  clear_has_relaymsgbytes();
}
inline const ::std::string& DataRelayReq::relaymsgbytes() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayReq.relayMsgBytes)
  return *relaymsgbytes_;
}
inline void DataRelayReq::set_relaymsgbytes(const ::std::string& value) {
  set_has_relaymsgbytes();
  if (relaymsgbytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgbytes_ = new ::std::string;
  }
  relaymsgbytes_->assign(value);
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayReq.relayMsgBytes)
}
inline void DataRelayReq::set_relaymsgbytes(const char* value) {
  set_has_relaymsgbytes();
  if (relaymsgbytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgbytes_ = new ::std::string;
  }
  relaymsgbytes_->assign(value);
  // @@protoc_insertion_point(field_set_char:jsbn.protoc.DataRelayReq.relayMsgBytes)
}
inline void DataRelayReq::set_relaymsgbytes(const void* value, size_t size) {
  set_has_relaymsgbytes();
  if (relaymsgbytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgbytes_ = new ::std::string;
  }
  relaymsgbytes_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:jsbn.protoc.DataRelayReq.relayMsgBytes)
}
inline ::std::string* DataRelayReq::mutable_relaymsgbytes() {
  set_has_relaymsgbytes();
  if (relaymsgbytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    relaymsgbytes_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.DataRelayReq.relayMsgBytes)
  return relaymsgbytes_;
}
inline ::std::string* DataRelayReq::release_relaymsgbytes() {
  clear_has_relaymsgbytes();
  if (relaymsgbytes_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = relaymsgbytes_;
    relaymsgbytes_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DataRelayReq::set_allocated_relaymsgbytes(::std::string* relaymsgbytes) {
  if (relaymsgbytes_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete relaymsgbytes_;
  }
  if (relaymsgbytes) {
    set_has_relaymsgbytes();
    relaymsgbytes_ = relaymsgbytes;
  } else {
    clear_has_relaymsgbytes();
    relaymsgbytes_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.DataRelayReq.relayMsgBytes)
}

// -------------------------------------------------------------------

// DataRelayRsp

// required .jsbn.protoc.ServiceTpye srcSrvType = 1;
inline bool DataRelayRsp::has_srcsrvtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void DataRelayRsp::set_has_srcsrvtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void DataRelayRsp::clear_has_srcsrvtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void DataRelayRsp::clear_srcsrvtype() {
  srcsrvtype_ = -1;
  clear_has_srcsrvtype();
}
inline ::jsbn::protoc::ServiceTpye DataRelayRsp::srcsrvtype() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayRsp.srcSrvType)
  return static_cast< ::jsbn::protoc::ServiceTpye >(srcsrvtype_);
}
inline void DataRelayRsp::set_srcsrvtype(::jsbn::protoc::ServiceTpye value) {
  assert(::jsbn::protoc::ServiceTpye_IsValid(value));
  set_has_srcsrvtype();
  srcsrvtype_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayRsp.srcSrvType)
}

// required .jsbn.protoc.ServiceTpye dstSrvType = 2;
inline bool DataRelayRsp::has_dstsrvtype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void DataRelayRsp::set_has_dstsrvtype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void DataRelayRsp::clear_has_dstsrvtype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void DataRelayRsp::clear_dstsrvtype() {
  dstsrvtype_ = -1;
  clear_has_dstsrvtype();
}
inline ::jsbn::protoc::ServiceTpye DataRelayRsp::dstsrvtype() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayRsp.dstSrvType)
  return static_cast< ::jsbn::protoc::ServiceTpye >(dstsrvtype_);
}
inline void DataRelayRsp::set_dstsrvtype(::jsbn::protoc::ServiceTpye value) {
  assert(::jsbn::protoc::ServiceTpye_IsValid(value));
  set_has_dstsrvtype();
  dstsrvtype_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayRsp.dstSrvType)
}

// optional .jsbn.protoc.CityID dstCityID = 3;
inline bool DataRelayRsp::has_dstcityid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void DataRelayRsp::set_has_dstcityid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void DataRelayRsp::clear_has_dstcityid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void DataRelayRsp::clear_dstcityid() {
  dstcityid_ = -1;
  clear_has_dstcityid();
}
inline ::jsbn::protoc::CityID DataRelayRsp::dstcityid() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayRsp.dstCityID)
  return static_cast< ::jsbn::protoc::CityID >(dstcityid_);
}
inline void DataRelayRsp::set_dstcityid(::jsbn::protoc::CityID value) {
  assert(::jsbn::protoc::CityID_IsValid(value));
  set_has_dstcityid();
  dstcityid_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayRsp.dstCityID)
}

// required fixed32 result = 4;
inline bool DataRelayRsp::has_result() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void DataRelayRsp::set_has_result() {
  _has_bits_[0] |= 0x00000008u;
}
inline void DataRelayRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void DataRelayRsp::clear_result() {
  result_ = 0u;
  clear_has_result();
}
inline ::google::protobuf::uint32 DataRelayRsp::result() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayRsp.result)
  return result_;
}
inline void DataRelayRsp::set_result(::google::protobuf::uint32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayRsp.result)
}

// optional string error_description = 5;
inline bool DataRelayRsp::has_error_description() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void DataRelayRsp::set_has_error_description() {
  _has_bits_[0] |= 0x00000010u;
}
inline void DataRelayRsp::clear_has_error_description() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void DataRelayRsp::clear_error_description() {
  if (error_description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_->clear();
  }
  clear_has_error_description();
}
inline const ::std::string& DataRelayRsp::error_description() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.DataRelayRsp.error_description)
  return *error_description_;
}
inline void DataRelayRsp::set_error_description(const ::std::string& value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
  // @@protoc_insertion_point(field_set:jsbn.protoc.DataRelayRsp.error_description)
}
inline void DataRelayRsp::set_error_description(const char* value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
  // @@protoc_insertion_point(field_set_char:jsbn.protoc.DataRelayRsp.error_description)
}
inline void DataRelayRsp::set_error_description(const char* value, size_t size) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:jsbn.protoc.DataRelayRsp.error_description)
}
inline ::std::string* DataRelayRsp::mutable_error_description() {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.DataRelayRsp.error_description)
  return error_description_;
}
inline ::std::string* DataRelayRsp::release_error_description() {
  clear_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = error_description_;
    error_description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void DataRelayRsp::set_allocated_error_description(::std::string* error_description) {
  if (error_description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_description_;
  }
  if (error_description) {
    set_has_error_description();
    error_description_ = error_description;
  } else {
    clear_has_error_description();
    error_description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.DataRelayRsp.error_description)
}

// -------------------------------------------------------------------

// NetProtocol

// optional fixed32 seq = 1;
inline bool NetProtocol::has_seq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NetProtocol::set_has_seq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NetProtocol::clear_has_seq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NetProtocol::clear_seq() {
  seq_ = 0u;
  clear_has_seq();
}
inline ::google::protobuf::uint32 NetProtocol::seq() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.seq)
  return seq_;
}
inline void NetProtocol::set_seq(::google::protobuf::uint32 value) {
  set_has_seq();
  seq_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.NetProtocol.seq)
}

// required .jsbn.protoc.CommandID commandID = 2;
inline bool NetProtocol::has_commandid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NetProtocol::set_has_commandid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NetProtocol::clear_has_commandid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NetProtocol::clear_commandid() {
  commandid_ = 0;
  clear_has_commandid();
}
inline ::jsbn::protoc::CommandID NetProtocol::commandid() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.commandID)
  return static_cast< ::jsbn::protoc::CommandID >(commandid_);
}
inline void NetProtocol::set_commandid(::jsbn::protoc::CommandID value) {
  assert(::jsbn::protoc::CommandID_IsValid(value));
  set_has_commandid();
  commandid_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.NetProtocol.commandID)
}

// optional .jsbn.protoc.RegisterReq registerReq = 3;
inline bool NetProtocol::has_registerreq() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NetProtocol::set_has_registerreq() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NetProtocol::clear_has_registerreq() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NetProtocol::clear_registerreq() {
  if (registerreq_ != NULL) registerreq_->::jsbn::protoc::RegisterReq::Clear();
  clear_has_registerreq();
}
inline const ::jsbn::protoc::RegisterReq& NetProtocol::registerreq() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.registerReq)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return registerreq_ != NULL ? *registerreq_ : *default_instance().registerreq_;
#else
  return registerreq_ != NULL ? *registerreq_ : *default_instance_->registerreq_;
#endif
}
inline ::jsbn::protoc::RegisterReq* NetProtocol::mutable_registerreq() {
  set_has_registerreq();
  if (registerreq_ == NULL) registerreq_ = new ::jsbn::protoc::RegisterReq;
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.NetProtocol.registerReq)
  return registerreq_;
}
inline ::jsbn::protoc::RegisterReq* NetProtocol::release_registerreq() {
  clear_has_registerreq();
  ::jsbn::protoc::RegisterReq* temp = registerreq_;
  registerreq_ = NULL;
  return temp;
}
inline void NetProtocol::set_allocated_registerreq(::jsbn::protoc::RegisterReq* registerreq) {
  delete registerreq_;
  registerreq_ = registerreq;
  if (registerreq) {
    set_has_registerreq();
  } else {
    clear_has_registerreq();
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.NetProtocol.registerReq)
}

// optional .jsbn.protoc.RegisterRsp registerRsp = 4;
inline bool NetProtocol::has_registerrsp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void NetProtocol::set_has_registerrsp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void NetProtocol::clear_has_registerrsp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void NetProtocol::clear_registerrsp() {
  if (registerrsp_ != NULL) registerrsp_->::jsbn::protoc::RegisterRsp::Clear();
  clear_has_registerrsp();
}
inline const ::jsbn::protoc::RegisterRsp& NetProtocol::registerrsp() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.registerRsp)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return registerrsp_ != NULL ? *registerrsp_ : *default_instance().registerrsp_;
#else
  return registerrsp_ != NULL ? *registerrsp_ : *default_instance_->registerrsp_;
#endif
}
inline ::jsbn::protoc::RegisterRsp* NetProtocol::mutable_registerrsp() {
  set_has_registerrsp();
  if (registerrsp_ == NULL) registerrsp_ = new ::jsbn::protoc::RegisterRsp;
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.NetProtocol.registerRsp)
  return registerrsp_;
}
inline ::jsbn::protoc::RegisterRsp* NetProtocol::release_registerrsp() {
  clear_has_registerrsp();
  ::jsbn::protoc::RegisterRsp* temp = registerrsp_;
  registerrsp_ = NULL;
  return temp;
}
inline void NetProtocol::set_allocated_registerrsp(::jsbn::protoc::RegisterRsp* registerrsp) {
  delete registerrsp_;
  registerrsp_ = registerrsp;
  if (registerrsp) {
    set_has_registerrsp();
  } else {
    clear_has_registerrsp();
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.NetProtocol.registerRsp)
}

// optional .jsbn.protoc.DataRelayReq dataRelayReq = 5;
inline bool NetProtocol::has_datarelayreq() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void NetProtocol::set_has_datarelayreq() {
  _has_bits_[0] |= 0x00000010u;
}
inline void NetProtocol::clear_has_datarelayreq() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void NetProtocol::clear_datarelayreq() {
  if (datarelayreq_ != NULL) datarelayreq_->::jsbn::protoc::DataRelayReq::Clear();
  clear_has_datarelayreq();
}
inline const ::jsbn::protoc::DataRelayReq& NetProtocol::datarelayreq() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.dataRelayReq)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return datarelayreq_ != NULL ? *datarelayreq_ : *default_instance().datarelayreq_;
#else
  return datarelayreq_ != NULL ? *datarelayreq_ : *default_instance_->datarelayreq_;
#endif
}
inline ::jsbn::protoc::DataRelayReq* NetProtocol::mutable_datarelayreq() {
  set_has_datarelayreq();
  if (datarelayreq_ == NULL) datarelayreq_ = new ::jsbn::protoc::DataRelayReq;
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.NetProtocol.dataRelayReq)
  return datarelayreq_;
}
inline ::jsbn::protoc::DataRelayReq* NetProtocol::release_datarelayreq() {
  clear_has_datarelayreq();
  ::jsbn::protoc::DataRelayReq* temp = datarelayreq_;
  datarelayreq_ = NULL;
  return temp;
}
inline void NetProtocol::set_allocated_datarelayreq(::jsbn::protoc::DataRelayReq* datarelayreq) {
  delete datarelayreq_;
  datarelayreq_ = datarelayreq;
  if (datarelayreq) {
    set_has_datarelayreq();
  } else {
    clear_has_datarelayreq();
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.NetProtocol.dataRelayReq)
}

// optional .jsbn.protoc.DataRelayRsp dataRelayRsp = 6;
inline bool NetProtocol::has_datarelayrsp() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void NetProtocol::set_has_datarelayrsp() {
  _has_bits_[0] |= 0x00000020u;
}
inline void NetProtocol::clear_has_datarelayrsp() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void NetProtocol::clear_datarelayrsp() {
  if (datarelayrsp_ != NULL) datarelayrsp_->::jsbn::protoc::DataRelayRsp::Clear();
  clear_has_datarelayrsp();
}
inline const ::jsbn::protoc::DataRelayRsp& NetProtocol::datarelayrsp() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.dataRelayRsp)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return datarelayrsp_ != NULL ? *datarelayrsp_ : *default_instance().datarelayrsp_;
#else
  return datarelayrsp_ != NULL ? *datarelayrsp_ : *default_instance_->datarelayrsp_;
#endif
}
inline ::jsbn::protoc::DataRelayRsp* NetProtocol::mutable_datarelayrsp() {
  set_has_datarelayrsp();
  if (datarelayrsp_ == NULL) datarelayrsp_ = new ::jsbn::protoc::DataRelayRsp;
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.NetProtocol.dataRelayRsp)
  return datarelayrsp_;
}
inline ::jsbn::protoc::DataRelayRsp* NetProtocol::release_datarelayrsp() {
  clear_has_datarelayrsp();
  ::jsbn::protoc::DataRelayRsp* temp = datarelayrsp_;
  datarelayrsp_ = NULL;
  return temp;
}
inline void NetProtocol::set_allocated_datarelayrsp(::jsbn::protoc::DataRelayRsp* datarelayrsp) {
  delete datarelayrsp_;
  datarelayrsp_ = datarelayrsp;
  if (datarelayrsp) {
    set_has_datarelayrsp();
  } else {
    clear_has_datarelayrsp();
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.NetProtocol.dataRelayRsp)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protoc
}  // namespace jsbn

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protoc_2eproto__INCLUDED
