// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc.proto

#ifndef PROTOBUF_protoc_2eproto__INCLUDED
#define PROTOBUF_protoc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace jsbn {
namespace protoc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_protoc_2eproto();
void protobuf_AssignDesc_protoc_2eproto();
void protobuf_ShutdownFile_protoc_2eproto();

class RegisterReq;
class RegisterRsp;
class NetProtocol;

enum CommandID {
  Heart_Beat = 0,
  Register_Req = 1,
  Register_Rsp = 65538
};
bool CommandID_IsValid(int value);
const CommandID CommandID_MIN = Heart_Beat;
const CommandID CommandID_MAX = Register_Rsp;
const int CommandID_ARRAYSIZE = CommandID_MAX + 1;

// ===================================================================

class RegisterReq : public ::google::protobuf::MessageLite {
 public:
  RegisterReq();
  virtual ~RegisterReq();

  RegisterReq(const RegisterReq& from);

  inline RegisterReq& operator=(const RegisterReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const RegisterReq& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RegisterReq* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RegisterReq* other);

  // implements Message ----------------------------------------------

  RegisterReq* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RegisterReq& from);
  void MergeFrom(const RegisterReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 cityID = 1;
  inline bool has_cityid() const;
  inline void clear_cityid();
  static const int kCityIDFieldNumber = 1;
  inline ::google::protobuf::uint32 cityid() const;
  inline void set_cityid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.RegisterReq)
 private:
  inline void set_has_cityid();
  inline void clear_has_cityid();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint32 cityid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static RegisterReq* default_instance_;
};
// -------------------------------------------------------------------

class RegisterRsp : public ::google::protobuf::MessageLite {
 public:
  RegisterRsp();
  virtual ~RegisterRsp();

  RegisterRsp(const RegisterRsp& from);

  inline RegisterRsp& operator=(const RegisterRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const RegisterRsp& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RegisterRsp* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RegisterRsp* other);

  // implements Message ----------------------------------------------

  RegisterRsp* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RegisterRsp& from);
  void MergeFrom(const RegisterRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required fixed32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::uint32 result() const;
  inline void set_result(::google::protobuf::uint32 value);

  // optional string error_description = 2;
  inline bool has_error_description() const;
  inline void clear_error_description();
  static const int kErrorDescriptionFieldNumber = 2;
  inline const ::std::string& error_description() const;
  inline void set_error_description(const ::std::string& value);
  inline void set_error_description(const char* value);
  inline void set_error_description(const char* value, size_t size);
  inline ::std::string* mutable_error_description();
  inline ::std::string* release_error_description();
  inline void set_allocated_error_description(::std::string* error_description);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.RegisterRsp)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_error_description();
  inline void clear_has_error_description();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* error_description_;
  ::google::protobuf::uint32 result_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static RegisterRsp* default_instance_;
};
// -------------------------------------------------------------------

class NetProtocol : public ::google::protobuf::MessageLite {
 public:
  NetProtocol();
  virtual ~NetProtocol();

  NetProtocol(const NetProtocol& from);

  inline NetProtocol& operator=(const NetProtocol& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const NetProtocol& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const NetProtocol* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(NetProtocol* other);

  // implements Message ----------------------------------------------

  NetProtocol* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const NetProtocol& from);
  void MergeFrom(const NetProtocol& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .jsbn.protoc.CommandID commandID = 1;
  inline bool has_commandid() const;
  inline void clear_commandid();
  static const int kCommandIDFieldNumber = 1;
  inline ::jsbn::protoc::CommandID commandid() const;
  inline void set_commandid(::jsbn::protoc::CommandID value);

  // optional .jsbn.protoc.RegisterReq registerReq = 2;
  inline bool has_registerreq() const;
  inline void clear_registerreq();
  static const int kRegisterReqFieldNumber = 2;
  inline const ::jsbn::protoc::RegisterReq& registerreq() const;
  inline ::jsbn::protoc::RegisterReq* mutable_registerreq();
  inline ::jsbn::protoc::RegisterReq* release_registerreq();
  inline void set_allocated_registerreq(::jsbn::protoc::RegisterReq* registerreq);

  // optional .jsbn.protoc.RegisterRsp registerRsp = 3;
  inline bool has_registerrsp() const;
  inline void clear_registerrsp();
  static const int kRegisterRspFieldNumber = 3;
  inline const ::jsbn::protoc::RegisterRsp& registerrsp() const;
  inline ::jsbn::protoc::RegisterRsp* mutable_registerrsp();
  inline ::jsbn::protoc::RegisterRsp* release_registerrsp();
  inline void set_allocated_registerrsp(::jsbn::protoc::RegisterRsp* registerrsp);

  // @@protoc_insertion_point(class_scope:jsbn.protoc.NetProtocol)
 private:
  inline void set_has_commandid();
  inline void clear_has_commandid();
  inline void set_has_registerreq();
  inline void clear_has_registerreq();
  inline void set_has_registerrsp();
  inline void clear_has_registerrsp();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::jsbn::protoc::RegisterReq* registerreq_;
  ::jsbn::protoc::RegisterRsp* registerrsp_;
  int commandid_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_protoc_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_protoc_2eproto();
  #endif
  friend void protobuf_AssignDesc_protoc_2eproto();
  friend void protobuf_ShutdownFile_protoc_2eproto();

  void InitAsDefaultInstance();
  static NetProtocol* default_instance_;
};
// ===================================================================


// ===================================================================

// RegisterReq

// required fixed32 cityID = 1;
inline bool RegisterReq::has_cityid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterReq::set_has_cityid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterReq::clear_has_cityid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterReq::clear_cityid() {
  cityid_ = 0u;
  clear_has_cityid();
}
inline ::google::protobuf::uint32 RegisterReq::cityid() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.RegisterReq.cityID)
  return cityid_;
}
inline void RegisterReq::set_cityid(::google::protobuf::uint32 value) {
  set_has_cityid();
  cityid_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.RegisterReq.cityID)
}

// -------------------------------------------------------------------

// RegisterRsp

// required fixed32 result = 1;
inline bool RegisterRsp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegisterRsp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegisterRsp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegisterRsp::clear_result() {
  result_ = 0u;
  clear_has_result();
}
inline ::google::protobuf::uint32 RegisterRsp::result() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.RegisterRsp.result)
  return result_;
}
inline void RegisterRsp::set_result(::google::protobuf::uint32 value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.RegisterRsp.result)
}

// optional string error_description = 2;
inline bool RegisterRsp::has_error_description() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegisterRsp::set_has_error_description() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegisterRsp::clear_has_error_description() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegisterRsp::clear_error_description() {
  if (error_description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_->clear();
  }
  clear_has_error_description();
}
inline const ::std::string& RegisterRsp::error_description() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.RegisterRsp.error_description)
  return *error_description_;
}
inline void RegisterRsp::set_error_description(const ::std::string& value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
  // @@protoc_insertion_point(field_set:jsbn.protoc.RegisterRsp.error_description)
}
inline void RegisterRsp::set_error_description(const char* value) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(value);
  // @@protoc_insertion_point(field_set_char:jsbn.protoc.RegisterRsp.error_description)
}
inline void RegisterRsp::set_error_description(const char* value, size_t size) {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  error_description_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:jsbn.protoc.RegisterRsp.error_description)
}
inline ::std::string* RegisterRsp::mutable_error_description() {
  set_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    error_description_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.RegisterRsp.error_description)
  return error_description_;
}
inline ::std::string* RegisterRsp::release_error_description() {
  clear_has_error_description();
  if (error_description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = error_description_;
    error_description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void RegisterRsp::set_allocated_error_description(::std::string* error_description) {
  if (error_description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete error_description_;
  }
  if (error_description) {
    set_has_error_description();
    error_description_ = error_description;
  } else {
    clear_has_error_description();
    error_description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.RegisterRsp.error_description)
}

// -------------------------------------------------------------------

// NetProtocol

// required .jsbn.protoc.CommandID commandID = 1;
inline bool NetProtocol::has_commandid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NetProtocol::set_has_commandid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NetProtocol::clear_has_commandid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NetProtocol::clear_commandid() {
  commandid_ = 0;
  clear_has_commandid();
}
inline ::jsbn::protoc::CommandID NetProtocol::commandid() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.commandID)
  return static_cast< ::jsbn::protoc::CommandID >(commandid_);
}
inline void NetProtocol::set_commandid(::jsbn::protoc::CommandID value) {
  assert(::jsbn::protoc::CommandID_IsValid(value));
  set_has_commandid();
  commandid_ = value;
  // @@protoc_insertion_point(field_set:jsbn.protoc.NetProtocol.commandID)
}

// optional .jsbn.protoc.RegisterReq registerReq = 2;
inline bool NetProtocol::has_registerreq() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NetProtocol::set_has_registerreq() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NetProtocol::clear_has_registerreq() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NetProtocol::clear_registerreq() {
  if (registerreq_ != NULL) registerreq_->::jsbn::protoc::RegisterReq::Clear();
  clear_has_registerreq();
}
inline const ::jsbn::protoc::RegisterReq& NetProtocol::registerreq() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.registerReq)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return registerreq_ != NULL ? *registerreq_ : *default_instance().registerreq_;
#else
  return registerreq_ != NULL ? *registerreq_ : *default_instance_->registerreq_;
#endif
}
inline ::jsbn::protoc::RegisterReq* NetProtocol::mutable_registerreq() {
  set_has_registerreq();
  if (registerreq_ == NULL) registerreq_ = new ::jsbn::protoc::RegisterReq;
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.NetProtocol.registerReq)
  return registerreq_;
}
inline ::jsbn::protoc::RegisterReq* NetProtocol::release_registerreq() {
  clear_has_registerreq();
  ::jsbn::protoc::RegisterReq* temp = registerreq_;
  registerreq_ = NULL;
  return temp;
}
inline void NetProtocol::set_allocated_registerreq(::jsbn::protoc::RegisterReq* registerreq) {
  delete registerreq_;
  registerreq_ = registerreq;
  if (registerreq) {
    set_has_registerreq();
  } else {
    clear_has_registerreq();
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.NetProtocol.registerReq)
}

// optional .jsbn.protoc.RegisterRsp registerRsp = 3;
inline bool NetProtocol::has_registerrsp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void NetProtocol::set_has_registerrsp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void NetProtocol::clear_has_registerrsp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void NetProtocol::clear_registerrsp() {
  if (registerrsp_ != NULL) registerrsp_->::jsbn::protoc::RegisterRsp::Clear();
  clear_has_registerrsp();
}
inline const ::jsbn::protoc::RegisterRsp& NetProtocol::registerrsp() const {
  // @@protoc_insertion_point(field_get:jsbn.protoc.NetProtocol.registerRsp)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return registerrsp_ != NULL ? *registerrsp_ : *default_instance().registerrsp_;
#else
  return registerrsp_ != NULL ? *registerrsp_ : *default_instance_->registerrsp_;
#endif
}
inline ::jsbn::protoc::RegisterRsp* NetProtocol::mutable_registerrsp() {
  set_has_registerrsp();
  if (registerrsp_ == NULL) registerrsp_ = new ::jsbn::protoc::RegisterRsp;
  // @@protoc_insertion_point(field_mutable:jsbn.protoc.NetProtocol.registerRsp)
  return registerrsp_;
}
inline ::jsbn::protoc::RegisterRsp* NetProtocol::release_registerrsp() {
  clear_has_registerrsp();
  ::jsbn::protoc::RegisterRsp* temp = registerrsp_;
  registerrsp_ = NULL;
  return temp;
}
inline void NetProtocol::set_allocated_registerrsp(::jsbn::protoc::RegisterRsp* registerrsp) {
  delete registerrsp_;
  registerrsp_ = registerrsp;
  if (registerrsp) {
    set_has_registerrsp();
  } else {
    clear_has_registerrsp();
  }
  // @@protoc_insertion_point(field_set_allocated:jsbn.protoc.NetProtocol.registerRsp)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protoc
}  // namespace jsbn

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protoc_2eproto__INCLUDED
